package com.mohamed.expenseguard;

import android.app.*;import android.os.*;import android.graphics.Color;import android.content.*;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class TaskActivity extends Activity {
    private ExpenseDbHelper db; private LinearLayout list; private final SimpleDateFormat fmt=new SimpleDateFormat("dd/MM/yyyy - hh:mm a",new Locale("ar"));
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new ExpenseDbHelper(this);if(new FirebaseSyncManager(this,db).currentUser()==null){Intent i=new Intent(this,MainActivity.class);i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);startActivity(i);finish();return;}getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);show();long id=getIntent().getLongExtra("taskId",-1);if(id>0){ExpenseDbHelper.TaskItem t=db.getTask(id);if(t!=null)edit(t);}}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);} private TextView tv(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(20,40,48));v.setGravity(Gravity.RIGHT);if(bold)v.setTypeface(null,1);v.setPadding(dp(6),dp(6),dp(6),dp(6));return v;}
    private void show(){LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(16),dp(16),dp(16),0);page.setBackgroundColor(Color.rgb(246,250,248));TextView title=tv("✅ قائمة المهام",27,true);page.addView(title);page.addView(tv("مستقلة عن المصروفات • أولويات • مواعيد • تكرار وتنبيهات",13,false));Button add=new Button(this);add.setText("＋ إضافة مهمة جديدة");add.setOnClickListener(v->edit(null));page.addView(add);ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);page.addView(sc,new LinearLayout.LayoutParams(-1,0,1));page.addView(bottomNav(),new LinearLayout.LayoutParams(-1,dp(70)));setContentView(page);refresh();}
    private LinearLayout bottomNav(){LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(4),dp(6),dp(4),dp(6));nav.setBackgroundColor(Color.WHITE);addNavButton(nav,"🧾\nمصروفاتي",v->{Intent i=new Intent(this,MainActivity.class);i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);startActivity(i);});addNavButton(nav,"✅\nالمهام",v->Toast.makeText(this,"أنت في قائمة المهام",Toast.LENGTH_SHORT).show());addNavButton(nav,"🪙\nالذهب",v->{startActivity(new Intent(this,GoldActivity.class));finish();});return nav;}
    private void addNavButton(LinearLayout nav,String label,View.OnClickListener click){Button b=new Button(this);b.setAllCaps(false);b.setText(label);b.setTextSize(12);b.setOnClickListener(click);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);lp.setMargins(dp(3),0,dp(3),0);nav.addView(b,lp);}
    private void refresh(){list.removeAllViews();List<ExpenseDbHelper.TaskItem> tasks=db.getTasks(true);if(tasks.isEmpty()){list.addView(tv("مفيش مهام لسه. اضغط إضافة وابدأ أول مهمة.",16,false));return;}for(ExpenseDbHelper.TaskItem t:tasks){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackgroundColor(t.completed==1?Color.rgb(232,240,235):Color.WHITE);String p=t.priority==3?"🔴 عاجلة":t.priority==2?"🟠 مهمة":"🟢 عادية";c.addView(tv((t.completed==1?"✓ ":"")+t.title,18,true));c.addView(tv(p+(t.dueAt>0?"  •  "+fmt.format(new Date(t.dueAt)):"  •  بدون موعد"),13,false));if(t.notes!=null&&!t.notes.trim().isEmpty())c.addView(tv(t.notes,13,false));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button done=new Button(this);done.setText(t.completed==1?"إعادة فتح":"تمت");done.setOnClickListener(v->{db.setTaskCompleted(t.id,t.completed!=1);if(t.completed!=1)TaskReminderReceiver.cancel(this,t.id);else if(t.dueAt>System.currentTimeMillis())TaskReminderReceiver.schedule(this,t.id,t.dueAt);refresh();});Button edit=new Button(this);edit.setText("تعديل");edit.setOnClickListener(v->edit(t));Button del=new Button(this);del.setText("حذف");del.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("حذف المهمة؟").setPositiveButton("حذف",(d,w)->{TaskReminderReceiver.cancel(this,t.id);db.deleteTask(t.id);refresh();}).setNegativeButton("إلغاء",null).show());actions.addView(done,new LinearLayout.LayoutParams(0,-2,1));actions.addView(edit,new LinearLayout.LayoutParams(0,-2,1));actions.addView(del,new LinearLayout.LayoutParams(0,-2,1));c.addView(actions);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(5),0,dp(7));list.addView(c,lp);}}
    private void edit(ExpenseDbHelper.TaskItem old){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(8),dp(16),dp(8));EditText title=new EditText(this);title.setHint("اسم المهمة *");EditText notes=new EditText(this);notes.setHint("ملاحظات، تفاصيل، روابط أو خطوات");notes.setMinLines(2);Spinner priority=new Spinner(this);priority.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"عادية","مهمة","عاجلة"}));Spinner repeat=new Spinner(this);String[] repeats={"بدون تكرار","كل نصف ساعة","كل ساعة","كل يوم","كل أسبوع","كل شهر"};repeat.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,repeats));final Calendar when=Calendar.getInstance();when.add(Calendar.HOUR_OF_DAY,1);Button date=new Button(this);date.setText("اختيار تاريخ ووقت التنبيه");CheckBox noDate=new CheckBox(this);noDate.setText("بدون موعد أو تنبيه");if(old!=null){title.setText(old.title);notes.setText(old.notes);priority.setSelection(Math.max(0,old.priority-1));if(old.dueAt>0)when.setTimeInMillis(old.dueAt);else noDate.setChecked(true);long r=old.repeatMinutes;repeat.setSelection(r==30?1:r==60?2:r==1440?3:r==10080?4:r==-1?5:0);date.setText(old.dueAt>0?fmt.format(new Date(old.dueAt)):"اختيار تاريخ ووقت التنبيه");}date.setOnClickListener(v->new DatePickerDialog(this,(dv,y,m,d)->{when.set(y,m,d);new TimePickerDialog(this,(tv,h,min)->{when.set(Calendar.HOUR_OF_DAY,h);when.set(Calendar.MINUTE,min);when.set(Calendar.SECOND,0);date.setText(fmt.format(when.getTime()));noDate.setChecked(false);},when.get(Calendar.HOUR_OF_DAY),when.get(Calendar.MINUTE),false).show();},when.get(Calendar.YEAR),when.get(Calendar.MONTH),when.get(Calendar.DAY_OF_MONTH)).show());box.addView(title);box.addView(notes);box.addView(tv("الأهمية",14,true));box.addView(priority);box.addView(date);box.addView(noDate);box.addView(tv("التكرار",14,true));box.addView(repeat);AlertDialog dialog=new AlertDialog.Builder(this).setTitle(old==null?"مهمة جديدة":"تعديل المهمة").setView(box).setPositiveButton("حفظ",null).setNegativeButton("إلغاء",null).create();dialog.setOnShowListener(x->dialog.getButton(-1).setOnClickListener(v->{String name=title.getText().toString().trim();if(name.isEmpty()){title.setError("اكتب اسم المهمة");return;}long[] vals={0,30,60,1440,10080,-1};long due=noDate.isChecked()?0:when.getTimeInMillis();long id=db.saveTask(old==null?null:old.id,name,notes.getText().toString().trim(),priority.getSelectedItemPosition()+1,due,vals[repeat.getSelectedItemPosition()],false);TaskReminderReceiver.cancel(this,id);if(due>0)TaskReminderReceiver.schedule(this,id,due);dialog.dismiss();refresh();}));dialog.show();}
}
