package com.mohamed.expenseguard;

import android.app.*;import android.os.*;import android.graphics.Color;import android.content.*;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.text.*;import java.util.*;import java.util.regex.*;

public class GoldActivity extends Activity {
    private ExpenseDbHelper db; private LinearLayout list; private TextView summary,status; private final int[] karats={24,21,18,14}; private final double[] buy=new double[4],sell=new double[4];
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new ExpenseDbHelper(this);getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);loadCache();show();refreshPrices();}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}private TextView tv(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(25,39,45));v.setGravity(Gravity.RIGHT);v.setPadding(dp(6),dp(5),dp(6),dp(5));if(bold)v.setTypeface(null,1);return v;}private String money(double v){return String.format(Locale.US,"%,.2f ج.م",v);}
    private void show(){LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(16),dp(16),dp(16),0);page.setBackgroundColor(Color.rgb(255,250,238));page.addView(tv("🪙 مدخراتي من الذهب",27,true));page.addView(tv("سجّل الوزن والعيار، والتطبيق يحسب قيمة البيع الحالية بالجنيه المصري.",13,false));LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(12),dp(10),dp(12),dp(10));head.setBackgroundColor(Color.WHITE);summary=tv("جاري الحساب...",21,true);status=tv("",12,false);head.addView(summary);head.addView(status);page.addView(head);LinearLayout buttons=new LinearLayout(this);Button add=new Button(this);add.setText("＋ إضافة ذهب");add.setOnClickListener(v->edit(null));Button update=new Button(this);update.setText("تحديث السعر");update.setOnClickListener(v->refreshPrices());buttons.addView(add,new LinearLayout.LayoutParams(0,-2,1));buttons.addView(update,new LinearLayout.LayoutParams(0,-2,1));page.addView(buttons);ScrollView sc=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sc.addView(list);page.addView(sc,new LinearLayout.LayoutParams(-1,0,1));page.addView(bottomNav(),new LinearLayout.LayoutParams(-1,dp(70)));setContentView(page);render();}
    private LinearLayout bottomNav(){LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setGravity(Gravity.CENTER);nav.setPadding(dp(4),dp(6),dp(4),dp(6));nav.setBackgroundColor(Color.WHITE);addNavButton(nav,"🧾\nمصروفاتي",v->{Intent i=new Intent(this,MainActivity.class);i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);startActivity(i);});addNavButton(nav,"✅\nالمهام",v->{startActivity(new Intent(this,TaskActivity.class));finish();});addNavButton(nav,"🪙\nالذهب",v->Toast.makeText(this,"أنت في مدخرات الذهب",Toast.LENGTH_SHORT).show());return nav;}
    private void addNavButton(LinearLayout nav,String label,View.OnClickListener click){Button b=new Button(this);b.setAllCaps(false);b.setText(label);b.setTextSize(12);b.setOnClickListener(click);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);lp.setMargins(dp(3),0,dp(3),0);nav.addView(b,lp);}
    private void loadCache(){for(int i=0;i<karats.length;i++){sell[i]=db.getDoubleSetting("gold_sell_"+karats[i],0);buy[i]=db.getDoubleSetting("gold_buy_"+karats[i],0);}}
    private int idx(int k){for(int i=0;i<karats.length;i++)if(karats[i]==k)return i;return 1;}
    private void render(){if(list==null)return;list.removeAllViews();double total=0,grams=0,cost=0;List<ExpenseDbHelper.GoldHolding> hs=db.getGoldHoldings();for(ExpenseDbHelper.GoldHolding g:hs){double value=g.grams*buy[idx(g.karat)];total+=value;grams+=g.grams;cost+=g.purchasePrice;LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(9),dp(12),dp(9));c.setBackgroundColor(Color.WHITE);c.addView(tv((g.label==null||g.label.isEmpty()?"ذهب":g.label)+" • عيار "+g.karat,17,true));c.addView(tv(String.format(Locale.US,"%.3f جرام  •  القيمة الحالية %s",g.grams,money(value)),14,false));if(g.purchasePrice>0)c.addView(tv("سعر الشراء المسجل: "+money(g.purchasePrice)+"  •  الفرق: "+money(value-g.purchasePrice),12,false));LinearLayout a=new LinearLayout(this);Button e=new Button(this);e.setText("تعديل");e.setOnClickListener(v->edit(g));Button d=new Button(this);d.setText("حذف");d.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("حذف البند؟").setPositiveButton("حذف",(x,w)->{db.deleteGoldHolding(g.id);render();}).setNegativeButton("إلغاء",null).show());a.addView(e,new LinearLayout.LayoutParams(0,-2,1));a.addView(d,new LinearLayout.LayoutParams(0,-2,1));c.addView(a);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),0,dp(6));list.addView(c,lp);}summary.setText("القيمة الحالية: "+money(total)+"\nإجمالي الوزن: "+String.format(Locale.US,"%.3f جرام",grams)+(cost>0?"\nالفرق عن الشراء: "+money(total-cost):""));if(hs.isEmpty())list.addView(tv("أضف السبائك أو الجنيهات أو المشغولات اللي محوشها.",15,false));}
    private void edit(ExpenseDbHelper.GoldHolding old){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText label=new EditText(this);label.setHint("الوصف (مثال: سبيكة 10 جرام)");Spinner k=new Spinner(this);String[] ks={"عيار 24","عيار 21","عيار 18","عيار 14"};k.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ks));EditText grams=new EditText(this);grams.setHint("الوزن بالجرام *");grams.setInputType(2|8192);EditText paid=new EditText(this);paid.setHint("إجمالي سعر الشراء (اختياري)");paid.setInputType(2|8192);if(old!=null){label.setText(old.label);k.setSelection(idx(old.karat));grams.setText(String.valueOf(old.grams));if(old.purchasePrice>0)paid.setText(String.valueOf(old.purchasePrice));}box.addView(label);box.addView(k);box.addView(grams);box.addView(paid);new AlertDialog.Builder(this).setTitle(old==null?"إضافة ذهب":"تعديل الذهب").setView(box).setPositiveButton("حفظ",(d,w)->{try{double g=Double.parseDouble(grams.getText().toString());double p=paid.getText().toString().trim().isEmpty()?0:Double.parseDouble(paid.getText().toString());if(g<=0)throw new Exception();db.saveGoldHolding(old==null?null:old.id,label.getText().toString().trim(),karats[k.getSelectedItemPosition()],g,p);render();}catch(Exception e){Toast.makeText(this,"اكتب وزن صحيح أكبر من صفر",Toast.LENGTH_LONG).show();}}).setNegativeButton("إلغاء",null).show();}
    private void refreshPrices(){status.setText("جاري تحديث أسعار eDahab...");new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL("https://edahabapp.com/").openConnection();c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestProperty("User-Agent","Mozilla/5.0 Masrofaty/2.20");StringBuilder html=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream(),"UTF-8"))){String line;while((line=r.readLine())!=null)html.append(line).append(' ');}String text=html.toString().replaceAll("<[^>]+>"," ").replace("&nbsp;"," ");for(int i=0;i<karats.length;i++){Pattern p=Pattern.compile("عيار\\s*"+karats[i]+".*?بيع\\s*:?\\s*([0-9,.]+).*?شراء\\s*:?\\s*([0-9,.]+)",Pattern.DOTALL);Matcher m=p.matcher(text);if(!m.find())throw new IOException("تعذر قراءة عيار "+karats[i]);sell[i]=Double.parseDouble(m.group(1).replace(",",""));buy[i]=Double.parseDouble(m.group(2).replace(",",""));db.setSetting("gold_sell_"+karats[i],String.valueOf(sell[i]));db.setSetting("gold_buy_"+karats[i],String.valueOf(buy[i]));}db.setSetting("gold_updated_at",String.valueOf(System.currentTimeMillis()));runOnUiThread(()->{status.setText(priceLine()+"\nآخر تحديث: "+new SimpleDateFormat("dd/MM/yyyy hh:mm a",new Locale("ar")).format(new Date())+" • المصدر: edahabapp.com • الحساب بسعر الشراء المنشور");render();});}catch(Exception e){runOnUiThread(()->{String last=db.getSetting("gold_updated_at","");status.setText("تعذر تحديث السعر الآن. معروض آخر سعر محفوظ"+(last.isEmpty()?" (لا يوجد سعر محفوظ بعد)":" بتاريخ "+new SimpleDateFormat("dd/MM/yyyy",new Locale("ar")).format(new Date(Long.parseLong(last))))+".");render();});}}).start();}
    private String priceLine(){StringBuilder s=new StringBuilder();for(int i=0;i<karats.length;i++){if(i>0)s.append("  |  ");s.append(karats[i]).append(": ").append(String.format(Locale.US,"%.0f",buy[i]));}return "سعر شراء الجرام: "+s;}
}
